[package]
name = "logger"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.8"
wascc-actor = { version="0.6.0", path = "../../wascc-actor" }

[profile.release]
# Optimize for small code size
opt-level = "s"
