[package]
name = "echo"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
#wascc-actor = "0.5.0"
wascc-actor = {path = "../../wascc-actor" }
serde = { version = "1.0.105", features = ["derive"]}

[profile.release]
# Optimize for small code size
opt-level = "s"
