[package]
name = "keyvalue"
version = "0.2.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = { version = "0.6.0",  path = "../../wascc-codec" }
log = "0.4.8"
env_logger = "0.7.1"